### ISSUE TITLE
PDF header and footer remove?

### ISSUE THREAD

**Issue by younussenn** [Ideolys/carbone#104]
Hi, i develop asp.net core project and i'm using carbone.io package. I create pdf file from .ods template. Everything is OK but created PDF file has header and footer. How to remove this? So is the reason for header and footer output is the carbone.io package?
Thanks.
![problemImg1](https://user-images.githubusercontent.com/46409298/100107703-ff5b6680-2e7a-11eb-85ca-97ef767fe08a.png)
![problemImg2](https://user-images.githubusercontent.com/46409298/100107705-fff3fd00-2e7a-11eb-9bc3-8bb272c9674c.png)

**Comment by steevepay** [comment]
Hello @younussenn, the header and footer appear because of your template, Carbone is not adding additional information on the PDF report.

**Comment by younussenn** [comment]
I got it. So thanks for reply.
