### ISSUE TITLE
Single file output for multiple documents? (batch process)

### ISSUE THREAD

**Issue by anthonywebb** [Ideolys/carbone#11]
Say I wanted to create invoices.  Is it possible to send an array of JSON objects to my invoice template and create an output file containing all of the invoices?  We tend to process things in batches (invoices, packing slips, etc) and it isn't practical to open and print each file individually.

**Comment by steevepay** [comment]
Hi @anthonywebb,

First, thanks for your issue !
Internally we have a solution but it is not implemented yet on Carbone.
We keep this enhancement in our roadmap, we will let you know about the progress.

**Comment by steevepay** [comment]
The batch process will be available on our SAS version.
