### ISSUE TITLE
[Bug Report]: Embedded LibreOffice Calc spreadsheet in slide doesn't pick up templating fills

### ISSUE THREAD

**Issue by RobotCaleb** [Ideolys/carbone#111]
**Environment**
Carbone Version: Carbone 2.1.1
Node Version: Node 10.23.2
Desktop OS: Ubuntu 18.04
Other: LibreOffice: 6.4.7.2

**Expected Behaviour**
Expect a table copied from a spreadsheet into another document (in this case a LibreOffice Impress slide) to work properly.

**Actual Behaviour**
Mustache template parameters in the table don't get filled.

**Steps to reproduce**
1. Open LibreOffice Calc, fill a cell with a mustache template
2. Copy the cell
3. In Impress -- Paste Special - choosing the LibreOffice Spreadsheet source
4. Attempt to replace the template parameter
5. Observe that replacement does not occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/113401/106231599-4af9fb80-61af-11eb-98e5-3149fa80b0ce.png)
```JavaScript
const fs = require('fs');
const carbone = require('carbone');

var data = 
{
    title: "A title",
    fill_this: "Please work",
};

carbone.render('./CopiedCell.odp', data, function(err, result) {
    if (err) return console.log(err);
    fs.writeFileSync('FailedTemplateReplace.odp', result);
    process.exit();
});
```
![image](https://user-images.githubusercontent.com/113401/106231621-55b49080-61af-11eb-99a0-727936f415ac.png)

**Reproduction Link / Code example**
I've included instructions above and sample files below.

[EmbeddedCell.zip](https://github.com/Ideolys/carbone/files/5891604/EmbeddedCell.zip)

**Comment by steevepay** [comment]
Hello @RobotCaleb, thank you for your feedback!
When a spreadsheet element (ODS) is pasted in a presentation file (ODP), it is creating a vector image (SVM file). Carbone can't inject data in an image. If you want to insert markers in a presentation template, you should create text boxes.

**Comment by RobotCaleb** [comment]
Cool! Thanks for informing me, I had no idea.
