### ISSUE TITLE
is it possible remove libreoffice dependency to convert pdf? like docx4j

### ISSUE THREAD

**Issue by softboy99** [Ideolys/carbone#116]
is it possible remove libreoffice dependency to convert pdf? like docx4j

**Comment by steevepay** [comment]
Hello @softboy99,

Carbone alone is not able to convert XML-based files into PDF.
We have tried multiple solutions to generate PDF from XML documents and LibreOffice is one of the most efficient.

If you need help, don't hesitate to reach us.

**Comment by softboy99** [comment]
so bad news.
