### ISSUE TITLE
Question about templates

### ISSUE THREAD

**Issue by pryratess** [Ideolys/carbone#12]
Hello,

I've spend some time trying to figure out what i'm doing wrong. I'm trying to create a template for some data and I want to create 2 tables. The problem is that in the output the two tables are merged together.
Anyway to fix this?
![carbone](https://user-images.githubusercontent.com/15173074/39878715-51a9b6c8-5479-11e8-80ad-cf65c9a54d35.jpg)

**Comment by steevepay** [comment]
Hi,

Can you share a simple reproduction template with some mock data ?
