### ISSUE TITLE
Dynamic color of value according to the passed value.

### ISSUE THREAD

**Issue by YednapNibas** [Ideolys/carbone#123]
I'm having trouble while defining dynamic color according to the value passed.

For example:-

if the value that's passed is less than 10 then the value should have the color red and greater than green. Something like this.

**Comment by steevepay** [comment]
Hello @YednapNibas, thank you for using Carbone!
You can follow this tutorial to apply colors according to conditions: https://carbone.crisp.help/en-us/article/replace-colors-dynamically-according-to-conditions-11dmn8l
Let me know if it works on your side.
Have a great day!

**Comment by YednapNibas** [comment]
> Hello @YednapNibas, thank you for using Carbone!
> You can follow this tutorial to apply colors according to conditions: https://carbone.crisp.help/en-us/article/replace-colors-dynamically-according-to-conditions-11dmn8l
> Let me know if it works on your side.
> Have a great day!

**Comment by YednapNibas** [comment]
Thank you for the suggestion. Is it applicable to values inside the next arrays? And my server always hung up when I tried to use {bindColor} in my template.

**Comment by steevepay** [comment]
Can you share a template example, a JSON dataset, and also a template of what you expect (without confidential information)? You can send it to the following address: support@carbone.io

**Comment by YednapNibas** [comment]
I've sent an email with template & JSON format. Thank you for you time.

**Comment by steevepay** [comment]
Solved and replied by email
