### ISSUE TITLE
 merging rows generating weird report with multiple rows after the merged rows. 

### ISSUE THREAD

**Issue by YednapNibas** [Ideolys/carbone#124]
**Environment**
Carbone SDK Version: Carbone 1.0.0
Node Version: Node 16.0.0

**Steps to reproduce**
1. Have multiple rows
2. Merge rows of first column & remaining rows are nested value of first-row value.

**Screenshots**
This is the template.
<img width="344" alt="Screen Shot 2021-05-14 at 5 55 47 PM" src="https://user-images.githubusercontent.com/34089225/118269124-084dfc00-b4de-11eb-923c-94ef39981b6f.png">

Generated report:
<img width="291" alt="Screen Shot 2021-05-14 at 5 56 00 PM" src="https://user-images.githubusercontent.com/34089225/118269157-169c1800-b4de-11eb-907d-c323aebe6312.png">

Hope it's understandable.

**Comment by steevepay** [comment]
Already answered but here is the solution for future persons coming on the thread.
Carbone can't keep a single merged column when it is mixed with a loop of rows, the column will be transformed as a row on the generated report. However it exists a solution, it is to create a table inside a table, such as:

<img width="852" alt="Screenshot 2021-05-17 at 17 33 16" src="https://user-images.githubusercontent.com/16964532/118515875-15fdbe80-b736-11eb-9f5c-6b468f664b74.png">

It is possible to remove the margin space between the inner table and the cell, follow these instructions for MS Word:
0. Right-click on the table > properties
1.  Select the tab "Table"
2. Click on the "Options..." button
3. Set the left and right margin at zero
4. Save 

<img width="672" alt="Screenshot 2021-05-17 at 17 35 03" src="https://user-images.githubusercontent.com/16964532/118516982-1c406a80-b737-11eb-8042-cd1d6377b012.png">

Then render the report with Carbone and the column will not be transformed or changed, voilà 🎉

**Comment by YednapNibas** [comment]
> Already answered but here is the solution for future persons coming on the thread.
> Carbone can't keep a single merged column when it is mixed with a loop of rows, the column will be transformed as a row on the generated report. However it exists a solution, it is to create a table inside a table, such as:
> 
> <img alt="Screenshot 2021-05-17 at 17 33 16" width="852" src="https://user-images.githubusercontent.com/16964532/118515875-15fdbe80-b736-11eb-9f5c-6b468f664b74.png">
> 
> It is possible to remove the margin space between the inner table and the cell, follow these instructions for MS Word:
> 
> 1. Right-click on the table > properties
> 2. Select the tab "Table"
> 3. Click on the "Options..." button
> 4. Set the left and right margin at zero
> 5. Save
> 
> <img alt="Screenshot 2021-05-17 at 17 35 03" width="672" src="https://user-images.githubusercontent.com/16964532/118516982-1c406a80-b737-11eb-8042-cd1d6377b012.png">
> 
> Then render the report with Carbone and the column will not be transformed or changed, voilà 🎉

Thank you for your solution to the gaping issue. However, I've tried in Ms. Word 2013 for left & right gaping. Unfortunately, it's not working in any of the editors I've used. And there's at least a gap in the inner table. I don't know why. Maybe I'm doing it in the wrong way. Can you please look into it. Thank you

![image](https://user-images.githubusercontent.com/34089225/118780660-00120a00-b8ac-11eb-9adb-09a71ea27203.png)
