### ISSUE TITLE
Nested arrays broke on first iteration

### ISSUE THREAD

**Issue by Tobino** [Ideolys/carbone#15]
Hello,

On example `node_modules/carbone/examples/movies.docx` it doesn't work, if you add an image on first loop. The image have to be inside the first loop, or the anchor's image.
Result loop stop on first iteration.

**Comment by devSwoop** [comment]
Hi,

Images loop cannot be done like that, it is more complicated... However, it is something we want to implement.

Thanks for your feedback :+1:
