### ISSUE TITLE
Windows support and file paths

### ISSUE THREAD

**Issue by rkaw92** [Ideolys/carbone#16]
Hi,
We're currently developing two features concurrently: [support for Windows](https://github.com/greatcare/carbone/tree/windows-support) and improved path detection for compatibility with OS-provided packages (not on any branch as of now) that should basically solve #10 .
Since the features are related (Windows needs path support, too), we'll need to base one of the change sets upon the other.
Should we prepare a cumulative pull request for both, or separate them (Windows support + Linux/Mac-only path detection, and then another changeset for adding Windows support to path detection) into different PRs?

**Comment by dcdamien** [comment]
@dgrelaud we will but we're also looking forward for Ideolys to put your upstream development of Carbone on GitHub not just merging from time to time 😅

**Comment by rkaw92** [comment]
Just a heads up: https://github.com/Ideolys/carbone/pull/17

**Comment by dcdamien** [comment]
@dbarros basic Windows support awaits merge in #17 but unfortunately this project looks unmaintained.

**Comment by devSwoop** [comment]
@dcdamien It is not, but the PR you're mentioning has to be done by @dgrelaud. We are working on Carbone and the first version of Carbone Studio (Carbone web UI) has been released last week, go check this out [here](https://app.carbone.io). However, I don't think that Windows support is a priority *for now*.

**Comment by rkaw92** [comment]
@dbarros We're considering it OK for development/testing of templates on Windows, but not for actually hosting a permanent rendering service reliably on that OS. Basically, it can render stuff, but I can't vouch for the process management / IPC part.
