### ISSUE TITLE
Stability of Carbone under load

### ISSUE THREAD

**Issue by jonathanoliver80** [Ideolys/carbone#18]
Hi,

We are looking at integrating Carbone into our corporate system to generate tens of thousands of PDFs from MS Word Doc templates per day.  We will obviously perform various load tests on this process but I was wondering if anyone has used this project under similar load?

Thanks!

JO

**Comment by dgrelaud** [comment]
Hi,

With the open source solution, you should be able to generate at least 30 000 pdf (of one page) per hour with a "normal" server (4 CPU, 8 Go of RAM, SSD disk ideally).

The most consuming process in Carbone is the conversion of document, DOCX (or something else) to PDF (or something else).

It the output format is the same as the input format (docx to docx, odt to odt), you can generate 300 000 reports (one page) per hour.

Let me know if you have any problem with such heavy load (memory problems or something less).
I've made a lot of work to make it as fast as possible.

Regards,
David.

**Comment by jonathanoliver80** [comment]
Hi David,

Those numbers seem perfectly reasonable and it makes sense that the PDF
creation would likely be the most difficult part of it--something that
isn't Carbone specific.  I am curious though, you mention the "open source
solution", is there a commercial version of it?

Regards,
Jonathan

**Comment by dgrelaud** [comment]
>  is there a commercial version of it?

Yes, we are working on it.
It includes more features (dynamic image and color insertion, UI, API, support...).
