### ISSUE TITLE
Add carbone to a docker image

### ISSUE THREAD

**Issue by samanehjmb** [Ideolys/carbone#19]
How can I add carbone to a docker image?
Since LibraOffice is required, is there any way to bunddle LibraOffice in Docker image as well?

Should I add following command to Dockerfile or package.json?
npm install carbone

**Comment by devSwoop** [comment]
Good news, a Docker image is available as **ideolys/carbone-env-docker**. You can see what's inside on https://github.com/Ideolys/carbone-env-docker.
