### ISSUE TITLE
Nested object trouble

### ISSUE THREAD

**Issue by Mika571** [Ideolys/carbone#2]
Hi,
I am having trouble with getting my nested JSON to work. 
````
{"Results": {
    "rheometer":[{
        "temperature":40,"shear_rate":0.1,"viscosity":0.1453},    
        {"temperature":40,"shear_rate":0.1585,"viscosity":0.1379},
        {"temperature":100,"shear_rate":100,"viscosity":0.01063}],
    "xrf":{"data":[{"element":"Ag","amount":58.19125,"units":"ppm"},
        {"element":"Al","amount":42.8444,"units":"ppm"},
        {"element":"Ba","amount":1121.773,"units":"ppm"},
        {"element":"Ca","amount":1878.824,"units":"ppm"},
        {"element":"Zn","amount":12.94434,"units":"ppm"}]    }}}
````
I am using the following in my word doc to iterate over the data

|         {d.Results.rheometer[i].temperature}   |  {d.Results.rheometer[i+1].temperature} |
|------------------------------------------------|---------------------------------------------|
| {d.Results.rheometer[i].viscosity:toFixed(2)} | {d.Results.rheometer[i+1].viscosity:toFixed(2)} | 

but I get the following error: `TypeError: Cannot read property 'rheometer' of undefined`. This is strange as the "Results" object definitely has the "rheometer"  property.

**Comment by dgrelaud** [comment]
Hi,

I have no errors on my side with your sample. Can you send me your template?

Thanks.
