### ISSUE TITLE
Page break support?

### ISSUE THREAD

**Issue by dbarros** [Ideolys/carbone#20]
Is there support for page breaks in templates? I tried by simply creating an ODT file (with repetitions) where each repetition I wanted to begin on a new page (inserting a page break to do so).

Is this something that's supported?

**Comment by devSwoop** [comment]
I think you can do this with the following template
```
{ d.array[i] }
*your content*
*PAGE_BREAK*
*LINE_BREAK*
{ d.array[i+1] }
```
Hope it will fit your needs :smile: 

*Carbone Studio is up (web UI for Carbone), you should take a look on https://app.carbone.io*

**Comment by dbarros** [comment]
Thanks, @devSwoop! I'll try this out.
