### ISSUE TITLE
Using carbone.io with a dockerised headless LibreOffice...

### ISSUE THREAD

**Issue by SamScholefield1** [Ideolys/carbone#21]
Hello Developers,

Thanks for carbone.io. We have been looking at carbone.io in the hope that we can use it with the following dockerised LibreOffice:
https://github.com/hannesdejager/docker-libreoffice-api
Which publishes itself on port 8100 of its IP address.

We see the general carbone parameters contain options for  factories &  startFactory but we can't see how to specify a remote existing headless LibreOffice.

If there is an option for this configuration, please will you let us know.

**Comment by devSwoop** [comment]
Hi,

Carbone runs LibreOffice instances itself and cannot use a remote LibreOffice one. If you want to use Carbone in a dockerized environment, you may use the the [docker image](https://github.com/Ideolys/carbone-env-docker) which contains everything needed to run Carbone (including LibreOffice).

The feature that you are mentioning is not on the todo, but it is an interesting one :wink:

**Comment by SamScholefield1** [comment]
Hi,

Thanks for the reply, we will try to use this docker image.
