### ISSUE TITLE
Rendering xlsx template issue when xlsx template has some merged cells at the bottom of the table

### ISSUE THREAD

**Issue by quocthanhnguyen** [Ideolys/carbone#22]
[template.xlsx](https://github.com/Ideolys/carbone/files/2759771/template.xlsx)

**Comment by steevepay** [comment]
Hi,

Can you share a simple reproduction template with some mock json data to reproduce ?

**Comment by officeutils** [comment]
This problem is alive stilll. You can make xlsx template where {d.cars[i].brand} is located in merged cell and another substitution at bottom of file in row without merged cells. You will get broken file layout completely. Your tests  does not cover merged cells case.

**Comment by x4viy** [comment]
I  still have the layout break when an XLSX template has merged cells near the middle of the sheet. 

If someone is facing the same problem, using an ODS version of the same template avoids the problem. Then I ask Carbone to convert the render to XLSX.

Steps:

1. Open your .xlsx template in LibreOffice and Save As → .ods.
2. Upload the .ods to Carbone
3. Call the render API with convertTo: "xlsx".
