### ISSUE TITLE
Processing has failed failed: Error during render: "Could not open document". https://app.carbone.io/#/studio

### ISSUE THREAD

**Issue by SamScholefield1** [Ideolys/carbone#24]
Good Morning,

When creating a new report on https://app.carbone.io/#/studio, I get this error and the preview fails to load.

Processing has failed failed: Error during render: "Could not open document".

The templates that I added on Monday are working correctly though.

Thanks.

Sam.

**Comment by devSwoop** [comment]
Hello Sam,

Is it a 100% replicable bug or is it a bit *random* ? Can you do what you want on the Studio now ?

**Comment by SamScholefield1** [comment]
Hello,

It seems to be working again now, but when it wasn't I created a new report, filled out the modal and then after trying to put some json in and render it, the error would appear in the bottom left.

Thanks.

**Comment by devSwoop** [comment]
Do you have this error every time or is it just with one report ? Unfortunately, I cannot reproduce this bug.

You can share your document to me by following these steps:

**Open the menu**
![screenshot](https://i.ibb.co/wSh8XR5/carbone-open-menu.png)

**Select your report**
![screenshot](https://i.ibb.co/q90vmTp/carbone-open-report.png)

**Open the menu and make it public**
![screenshot](https://i.ibb.co/b1HZYB0/carbone-open-reprot-menu.png)
![screenshot](https://i.ibb.co/ZN0r8NC/carbone-open-report-menu-public.png)

**Re-open the menu to copy the public link**
![screenshot](https://i.ibb.co/89zgZNd/carbone-open-report-menu-link.png)

Then give me the link and I will be able to see (and only see) your report with your template and your data. Note that everyone will be able to see your shared report with this *unique* link. You can "unshare"  your report by making it private.

**Comment by YednapNibas** [comment]
> Hello Sam,
> 
> Is it a 100% replicable bug or is it a bit _random_ ? Can you do what you want on the Studio now ?

It's random.

**Comment by steevepay** [comment]
Hello, when the error "Could not open document" occurs, it is because the template got a **design issue** and when Carbone renders the document, it created a corrupted file. It is not coming from the Node SDK.
