### ISSUE TITLE
Processing .docx template with table of contents fails

### ISSUE THREAD

**Issue by mcjon3z** [Ideolys/carbone#25]
Inserting a table of contents in a word .docx template causes processing to fail with the following errors:
```
Error: getSubstitutionFunction: Impossible to generate the XML builder.
SyntaxError: Invalid Unicode escape sequence
...
```

**Comment by devSwoop** [comment]
Can you please provide all your data (docx template and json data) ?

**Comment by lixaotec** [comment]
Dear, 

Can you provide me samples of odt to build automatically a summary?

I couldnt get it working, is it possible, like word does?

Thanks

**Comment by devSwoop** [comment]
Please open a new issue if you got any problem with Carbone, I'd be glad to help you, but I should have closed this one already :wink:

**Comment by mcjon3z** [comment]
This was the fix that was emailed to me in case anybody else has the same problem. Note that the option to correct is in OpenOffice; I could not find a similar setting in MS word...

> Your template has a read-only block: the Table of Contents. This is a bit weird but Carbone seems not to handle it properly and throws a non-friendly error. I just removed the protection by right clicking on the Table of Contents block (with the grey background) > Edit index > Uncheck Protected against manual changes, and save the document. I am now able to render your report with your template and your data (see the attachment).
