### ISSUE TITLE
DOCX to PDF conversion use only 1 worker even configured to multiple worker

### ISSUE THREAD

**Issue by icesk127** [Ideolys/carbone#26]
Hi, 
I'm facing a problem with pdf conversion is very slow. I'm using carbone to generate a document from docx and convert to pdf at a time. A docx file contains around 400 pages(~15 MB file size of docx). I've configured carbone to use 3 LibreOffice workers. It takes about an hour to complete conversion.

I figure out that only 1 worker is using 99% CPU usage and the other process is using 0% CPU Usage.

Has anyone facing this issue? How can I config the carbone to accerelate pdf conversion by using every worker?

System
Amazon EC2 t2.medium 
OS: Ubuntu Server 18.04
LibreOffice_5.3.2.2_Linux_x86-64_deb

![1548386442636](https://user-images.githubusercontent.com/1989143/51724540-67c73a00-2090-11e9-8b48-6685188f1131.jpg)

**Comment by devSwoop** [comment]
Hi,

The conversion process is something very slow by itself and cannot be splitted into several workers: LibreOffice handles operations in one single process.

If you want to split the load into workers, you have to give more than 1 file to Carbone, allowing it to use all the LibreOffice workers available.
