### ISSUE TITLE
Request for async formatter function support so we can query async data through formatter functions.

### ISSUE THREAD

**Issue by jason-medeiros** [Ideolys/carbone#29]
I'd appreciate it a lot if the project would support async function formatters, because then my formatter routines could make network requests/db requests to autopopulate common entries.  Just maybe have a check on the formatter prototype so it awaits if the formatter function is detected to be async. 

It would be even MORE rad if substitution values were checked prior to substitutions if they were a async/function type, and were called directly to generate values.

eg.  data.value_to_substitute = async function()
{
    return "some dynamic value here";
}

and in the ODT document you'd have something like {d.value_to_substitute} where it generates the value by calling the async routine in await.

**Comment by devSwoop** [comment]
Executing code from outside can be dangerous, how can we be sure that the given code does good things ? This feature should not be available for SaaS tools like Carbone Studio. Also the given data object must be a JSON object, you cannot store function inside as you can do with pure JS object (unless I misunderstood your use case). We could `eval` the code, but this is a bit disgusting, isn't it ?

Also, Carbone renders data, nothing else. I do not think this type of logic should be implemented, even if this is a cool feature, this logic should be on your server: before calling Carbone.

**Comment by jason-medeiros** [comment]
> Executing code from outside can be dangerous, how can we be sure that the given code does good things ? This feature should not be available for SaaS tools like Carbone Studio. Also the given data object must be a JSON object, you cannot store function inside as you can do with pure JS object (unless I misunderstood your use case). We could `eval` the code, but this is a bit disgusting, isn't it ?
> 
> Also, Carbone renders data, nothing else. I do not think this type of logic should be implemented, even if this is a cool feature, this logic should be on your server: before calling Carbone.

I'm talking about in-process, not SaaS.  Like directly from carbone.render().  I'm not interested in the SaaS product as it does not meet my needs.

**Comment by devSwoop** [comment]
If you want to use it on your own, ok, there is no security issue.  
However, I still think that this process should not be on Carbone's side because this logic could and should be done before calling Carbone.
