### ISSUE TITLE
Font seems to mess To Calibri (From Open Sans)

### ISSUE THREAD

**Issue by lixaotec** [Ideolys/carbone#32]
Dear, 

Its seem that it is not respecting original font from template. 

I used Open Sans, and when I export to docx the font seems changed to Calibri.

What am I doind wrong? Or is it a liitation?]

Thanks

**Comment by devSwoop** [comment]
Hi,  
are you using [Carbone Studio](https://app.carbone.io) or Carbone itself ?

**Comment by lixaotec** [comment]
Hey there, 

Carbone Studio

**Comment by lixaotec** [comment]
Follow my template for you to eval with the simple example of products in carbone studio

[sample_template.zip](https://github.com/Ideolys/carbone/files/3095479/sample_template.zip)

**Comment by devSwoop** [comment]
Our server doesn't have Open Sans installed, so I guess that Libreoffice will choose the first available font which is Calibri. I'll see if there is a way to embed the font in the *odt*, if not, we'll have to think about it 😉

**Comment by steevepay** [comment]
First, thanks for the feedback @lixaotec.
Some update, we will install the most used fonts into our Carbone servers (Calibri too).
Nevertheless, this issue does not concerns the carbone project on Github. 
If you want to talk about Carbone Studio or Carbone Render, tchat with us through Crisp (bottom right tchat on carbone.io)!
