### ISSUE TITLE
Font issue with Carlito.

### ISSUE THREAD

**Issue by iandesj** [Ideolys/carbone#33]
I've been using the node.js library and it appears that when I use Carlito as the font in my .ODT template, It's writing with DejaVuSans instead. I have tried several packaged Libreoffice fonts.

**Comment by devSwoop** [comment]
Is the font name written *in italic* when you're designing your template, like this ?
![Screenshot](https://i.ibb.co/9422Br0/carlito.png)
If it is, the font is not installed on the computer and DejaVu Sans will be used (this is the default one).  
I tried to use different fonts, default and downloaded ones (Impact, Comic Sans, Fira code), and the font in the rendered document was the expected one.

You shouldn't have any issue if you're using installed font.

**Comment by iandesj** [comment]
I'm going to close this issue. I didn't have the font installed on my linux box. I was using carbone + unoconv; where unoconv needed the font.
