### ISSUE TITLE
Barcode support

### ISSUE THREAD

**Issue by seteq** [Ideolys/carbone#34]
Is it possible to use barcodes or QR codes? Has anyone already tried that?

**Comment by seteq** [comment]
I just installed an Code128 barcode font to the linux system and it's working very nice.

**Comment by so1ver** [comment]
> I just installed an Code128 barcode font to the linux system and it's working very nice.

Hi, can you explain more detail how you did that?
Because after I added code128 font I can get barcode on document but noone scanner can't read it.
Thank you.

**Comment by steevepay** [comment]
Hi, Carbone Render and Carbon Studio (Entreprise Edition) are actually supporting ean13, code39 and ean8 barcodes. We will add code128 support really soon.
