### ISSUE TITLE
What if I have to merge existing PDF?

### ISSUE THREAD

**Issue by MonDeveloper** [Ideolys/carbone#35]
First of all, guys, congrats, u did a terrific job!

With our requirements in mind there are a couple of things I'm still not able to map with your tool, could you help me understanding if there's a way for the main one?

**Merge of existing Documents**
 Our source of informations are:
   - a raw Json (_which can be mapped as you clearly describe_) 
   - many photos (_we can see a way into your documentation_)
   - other docs / pdf (_to be merged in a specific order_)

The requirement is to be able to attach those "other docs" at a certain position of the final document, sometimes "other docs" are PDF with the same format of the ODT (e.g: Vertical A4), othertimes they could be (DOC, DOCX, TIFF, TXT) with different graphic format: (Horizontal, Letter, Legal), etc....

Thanks,
mM

**Comment by devSwoop** [comment]
Hi,
You can't merge documents like this with Carbone, inserting documents like json data cannot be done easily and needs a bit more reflexion.  
We do have some ideas to merge documents, but not that way.

Thanks for sharing your use case, we'll definitely think about it (for now we're focusing on a new version of the [Studio](https://app.carbone.io)) !
