### ISSUE TITLE
Corrupt PDF 

### ISSUE THREAD

**Issue by abdu355** [Ideolys/carbone#37]
Used the recommended Dockerfile, getting a corrupt PDF every time I render a report.
docx & odt open nicely with no problem.

```
FROM node:8

WORKDIR /tmp
RUN wget http://download.documentfoundation.org/libreoffice/stable/6.1.5/deb/x86_64/LibreOffice_6.1.5_Linux_x86-64_deb.tar.gz -O libo.tar.gz
RUN apt update \
    && apt install -y libxinerama1 libfontconfig1 libdbus-glib-1-2 libcairo2 libcups2 libglu1-mesa libsm6 unzip \
    && tar -zxvf libo.tar.gz
WORKDIR LibreOffice_6.1.5.2_Linux_x86-64_deb/DEBS
RUN dpkg -i *.deb

WORKDIR /home/node

COPY package.json .
RUN npm install --quiet

COPY . .
```

![image](https://user-images.githubusercontent.com/12097274/57587978-89084500-751e-11e9-8d96-91fd8a9d0e98.png)

Code used in app:

```
let options = {
  convertTo: "pdf" //can be docx, txt, ...
};

carbone.render(
        appRoot + "/templates/sample_template.odt",
        dataJSON,
        options,
        function(err, result) {
          if (err) {
            return console.log(err);
          }
          // write the result
          fs.writeFileSync(appRoot + "/templates/sample.pdf", result);
          console.log(result);
          return result;
        }
      );
```

**Comment by steevepay** [comment]
Hi,

Do you still have the problème ?
If yes, can you share a simple reproduction template with some mock json data to reproduce ?

**Comment by rubenstz** [comment]
Hello everyone,
I have the same problem and it still happens, in fact the conversion to PDF does not work!

What happens is that the result file is an ODT type, for testing you can rename or just put the extension .odt in the result.pdf file that will open with LIBREOFFICE without the corrupted message.

Before you ask, I also put options {convertTo: "pdf"}

**Comment by steevepay** [comment]
Hi @rubenstz,

Can you share the template and the data used to reproduce the issue?
Also, which version of Carbone, Node, OS are you using?

**Comment by rubenstz** [comment]
Hi @steevepay, I managed to resolve by reinstalling my version of libreoffice, I even made it work on a version of Windows 10 pointing the following path: C: \ Program Files \ LibreOffice \ program \
Everything working now, thanks!
