### ISSUE TITLE
Large document generation/inserting dynamic content.

### ISSUE THREAD

**Issue by jason-medeiros** [Ideolys/carbone#39]
Is there a streaming interface for carbone?  Essentially I'm trying to generate massive documents, but the problem is that at points, I have to load in more data than exists physical memory on the machine.  

To get around this, I'm having to load chunks of data, write the data to the document, insert new carbone elements into the document at the tail of the document, then repeat the process in a loop.

The issue with this, is that I can't insert anything other than plain text elements.  I'd like to be able to **insert dynamic tables** into the document by writing carbone elements but it seems there is no functionality for that? 

Am I mistaken?  Or is this the case?  If so, are there any plans for a streaming interface for carbone?  One that could generate huge reports without having to load the full data into memory?

**Comment by devSwoop** [comment]
Carbone does not provide a streaming interface, everything is loaded in the RAM.  
Data passed to Carbone must be a JSON object: we can't provide a stream in the data object.

I think Carbone was not designed to handle this kind of usage.

Inserting a table is a "low-level" operation, you have to manipulate your document (which is XML files), and Carbone does not provide this type of API.

Unfortunately, implementing what you need would, to me, involve too much work.

**Comment by steevepay** [comment]
To close the issue, if you need performances without being limited and without using your machine, you can checkout our Carbone Render API that generate quickly your massive documents with low latency: [Carbone Api Reference.](https://carbone.io/api-reference.html)
