### ISSUE TITLE
LibreOffice not fund on windows

### ISSUE THREAD

**Issue by CMAraujo87** [Ideolys/carbone#41]
When trying to convert to pdf file, I got an error telling me that LibreOffice is not installed.

Scenario:
OS: Windows 7 SP1 (x64)
LibreOffice Version: 6.2.5.2 (x64)
soffice.exe Path: 'C:/Program Files/LibreOffice/program/soffice.exe'

The current filter cannot find this path: (Line 497 of file "converter.js")
`var _windowsDirnamePattern = /^LibreOffice \d+(?:\.\d+)?$/i;` 

I could correct it locally by changing it to:
`var _windowsDirnamePattern = /^LibreOffice( \d+(?:\.\d+)?)?$/i;`

**Comment by marcquesmouton** [comment]
THANK you soooo much @CMAraujo87 you saved me

**Comment by buster95** [comment]
I don't like idea that depends on LibreOffice

**Comment by dgrelaud** [comment]
I should fix it on Windows. Sorry for that. 

> I don’t like idea that depends on LibreOffice

Libreoffice is not mandatory if you do not convert the template to another format. 

At the beginning, I tried to avoid LibreOffice because I wanted a tool really light and highly performant. But after many researches, I have never found a solution to  convert a document more reliable than LibreOffice and which can run everywhere.

**Comment by buster95** [comment]
> I should fix it on Windows. Sorry for that.
> 
> > I don’t like idea that depends on LibreOffice
> 
> Libreoffice is not mandatory if you do not convert the template to another format.
> 
> At the beginning, I tried to avoid LibreOffice because I wanted a tool really light and highly performant. But after many researches, I have never found a solution to convert a document more reliable than LibreOffice and which can run everywhere.

yes I know but, I believe that it possible change  file type buffer into another file type buffer, for example exists a library word2pdf that convert docx files into pdf, too carbone developers should be add possibility for use dataUri with base64 format

**Comment by buster95** [comment]
Do you research if you can included LibreOffice libraries for each OS?? without had LibreOffice installation

**Comment by steevepay** [comment]
@buster95 If you don't want library installation, you should use Docker by using our "ideolys/carbone-env-docker" image, [check out](https://hub.docker.com/r/ideolys/carbone-env-docker). It's a Carbone environment ready to use: node 8 image with Libreoffice installed. Reach me if you need help to setup.
Also, feel free to Fork the project and submit Pull Requests to make improvements !

**Comment by MohammedHafiz** [comment]
can we use carboneoio with out LibreOffice ??  I want to use this in my project , so there any issues if I use carboneio without LibreOffice

**Comment by CMAraujo87** [comment]
> can we use carboneoio with out LibreOffice ??  I want to use this in my project , so there any issues if I use carboneio without LibreOffice

Carboneio uses LibreOffice to convert the document into PDF. You won't need it if you don't want to convert or if you'll use another tool for the conversion.
