### ISSUE TITLE
TypeError on null fields

### ISSUE THREAD

**Issue by edgrasso** [Ideolys/carbone#42]
When the template contains a Placeholder with nested properties, everything works fine if the path described by the placeholder exists or if one (or more) of the listed properties does not exist at all, but a TypeError occurs if one of the properties is null.

As an instance, considering the placeholder {d.A.B.C}

{ "A" : { "B" : { "C" : 1 } } } => Ok
{ "A" : { } } => Ok
{ "A" : { "B" : null }} => TypeError: Cannot read property 'C' of null

Mainly, the issue was due to the use of the operator "!==" to perform the due checks (null !== undefined => true).

Moreover a null/undefined check is missing at all in "getBuilderFunction" method, in the section responsible for the composition of the code related to arrays initialization (rows 474 and 477).

**Comment by rkaw92** [comment]
Hi, fellow user here. We've developed a branch that adds dynamic key support, and incidentally, also tackles this issue: https://github.com/greatcare/carbone/commit/e2a143bc39062b44c32c32d14c33f4048347c4da

Can you try that and tell us if it solves the problem for you?

**Comment by edgrasso** [comment]
Hi, thanks for your reply.
Your branch partially solves the issue but, as I stated in the last two lines of my previous post, there is a null-check that is missing at all in the code section related to arrays initialization so, if your template is referencing an array and it does not exist in the bound model, the library throws a TypeError.

**Comment by adgelbfish** [comment]
any update on this?

**Comment by steevepay** [comment]
Hi @adgelbfish, here is an update with Carbone: https://github.com/Ideolys/carbone/issues/9#issuecomment-615142315. We will focus on this issue after shipping the new version.

**Comment by steevepay** [comment]
It has been fixed in the lastest release v2.0.0, I close the issue.
