### ISSUE TITLE
In Conditioned output, the characters after comma is not getting printed on the document.

### ISSUE THREAD

**Issue by PrashanthGowda** [Ideolys/carbone#44]
I have a condition where ifEqual to 1 it should print 

> Some sentence, some more sentences.

I am doing this, `{d.sentenceExist:ifEqual(1, 'Some sentence, some more sentences.')}`

In the output, if the condition is true, only the text before the comma is getting printed.

That means, the output is, 

> Some sentence

instead of 

> Some sentence, some more sentences.

**Comment by steevepay** [comment]
Hi @PrashanthGowda,

First, thanks for the bug report !
I just have reproduced the problem and we will fix this.
Meanwhile, feel free to fork the project and contribute :)

**Comment by ZFLloyd** [comment]
Any news on this issue @steevepay ?

**Comment by steevepay** [comment]
It is fixed on the new version, check out the [v2 branch on Github](https://github.com/Ideolys/carbone/tree/v2.0) or directly NPM: `npm install carbone@2.0.0-beta.0`
The changes with examples are available on the [changelog](https://github.com/Ideolys/carbone/blob/v2.0/CHANGELOG.md).

**Comment by steevepay** [comment]
The fix has been publish on master.
