### ISSUE TITLE
Support for ranges in Excel

### ISSUE THREAD

**Issue by mcjon3z** [Ideolys/carbone#49]
Not sure if this is possible or not, but it would be nice to be able to set up a table containing tags as a named range or full-on Excel table that could then be referenced by other items such as charts and pivot tables once the data is populated (note previous issue relating to pivot tables corrupting spreadsheet).

Currently, a named range / table does not expand to include all data that is populated - it remains the same size as it was originally defined.

**Comment by steevepay** [comment]
Hi @mcjon3z 
We are working on it.
I close the issue, duplicate from #6.
