### ISSUE TITLE
[Bug Report]: When you have over 2 levels of inner tables in your template you are no longer able to use tokens outside of the most inner table

### ISSUE THREAD

**Issue by thilux** [Ideolys/carbone#54]
My template (attached) has the following structure:

![image](https://user-images.githubusercontent.com/4541251/68827332-6afad900-0656-11ea-88fb-fdea03ab777a.png)

The fact that there are tables with inner tables, prevents me from being able to use tokens outside those inner tables. The part highlighted in orange in the screenshot above, is already enough for Carbone to generate an invalid DOCX file, even though it throws no errors at all. Attempting to open the generated file on  MS Word or LibreOffice Writer, gives the following error:

![image](https://user-images.githubusercontent.com/4541251/68827415-bc0acd00-0656-11ea-867a-f5fc9e4191c8.png)

If I remove the tokens that are outside that structure (from the orange highlighted part in the screenshot above and everything beneath it), the generated DOCX works just fine.

The template used for test is [carbone_play.docx](https://github.com/Ideolys/carbone/files/3844544/carbone_play.docx) and the data used for rendering is [data.txt](https://github.com/Ideolys/carbone/files/3844540/data.txt)

**Environment**
Carbone Version: 1.2.0
Node Version: 10.14.2
Browsers: [e.g. chrome 22]
Server OS: Alpine 3.9

**Expected Behaviour**
Carbone should be able to populate the attached template.

**Actual Behaviour**
The result of carbone render generates an invalid word document that can't be opened.

**Steps to reproduce**
Steps to reproduce the bug:
1. Use the attached template.
2. Use the attached json request for transformation.
3. Try to open the resulting word document with MS Word or Libreoffice Writer.
4. You should see a message stating the resulting document is invalid.

**Comment by steevepay** [comment]
Hi @thilux,

First thanks for your message.
It's completely normal to not able to display `{d.person[i].name}` (The part highlighted in orange) because the `i` keyword is only used for repetitions, it should be always followed by the key `i+1`. By these 2 keys, Carbone will find automatically the pattern to repeat.

However, the generated file should not be corrupted. Your URLs are not found, can you share again the template and the data used?

**Comment by thilux** [comment]
Hi @steevepay ,

Thanks for your response.

Here are the attachments again: 
[data.txt](https://github.com/Ideolys/carbone/files/3859694/data.txt)
[carbone_play.docx](https://github.com/Ideolys/carbone/files/3859695/carbone_play.docx)
