### ISSUE TITLE
[Feature Request]: Examples for Dynamic Data + Dynamic Color Changes

### ISSUE THREAD

**Issue by zhakamizhako** [Ideolys/carbone#55]
Hello. I seem to be having trouble following your documentation regarding dynamic Color changes. We may need a few dynamic color markings on our generated Documents / PDF. I tried placing a few bindColor() calls at the template files we're editing. The dynamic data works, but bindColor seems to just imprint at the document. Possible that i may have misunderstood the documentation, but i think it's better for some example templates involving the color manipulation. We're using Word/ODT Format templates, to PDF conversion.

I would like to ask a few example templates with dynamic Data with Dynamic Color manipulations.

Thank you, good day.

**Comment by steevepay** [comment]
Hello @zhakamizhako,

The bindColor marker is only available on Carbone Studio or Carbone Render (API).
For example, our goal is to bind a red color `#FF0000` to the `{d.myText}` marker. Here is a docx template example:
<img width="419" alt="Screenshot 2019-11-18 at 14 21 49" src="https://user-images.githubusercontent.com/16964532/69055823-fd143000-0a0e-11ea-8b28-910667df96c8.png">
- The color `#00FFFF` is applied to the marker `{d.myText}`: it is used by `bindColor()` to identify the marker to replace with.
- At the end of the template, add the bindColor marker with 2 parameters: 
  - The color you want to replace on the template
  - The format of color you want to apply (#hexa, hexa, color, rgb, hsl)
 - Then, assign to the bindColor marker a new color. It should be formatted according to what you have defined on the parameters. In our example, `{d.color}` is a hexadecimal  `#FF0000`.
- On Carbone Studio, upload your template then add the JSON data to inject:
```JSON
{
  "myText": "Hello world",
  "color": "#FF0000"
}
```
Finally, the report preview (on the right) should display the report:
<img width="382" alt="Screenshot 2019-11-18 at 16 05 30" src="https://user-images.githubusercontent.com/16964532/69063733-48cdd600-0a1d-11ea-8f2e-3c3e21af2d14.png">

[Here is the `bindColor` documentation.](https://carbone.io/documentation.html#manage-color-dynamically)
Reach me if you need help.

**Comment by steevepay** [comment]
Hi there, I'm closing the issue since @zhakamizhako hasn't yet responded. Therefore, we assume you have resolved the problem. Don't worry though, if you need help again, let us know with a comment and we'll be happy to reopen the issue.
