### ISSUE TITLE
Being able to create new sheets using templates

### ISSUE THREAD

**Issue by JVaghela-Fintech** [Ideolys/carbone#56]
Hi, We are looking to use carbone in one of our projects and are going through evaluating different features, We are trying to customize the number of sheets and sheet names using the templates but not sure how to do this, Can someone please help if you think this is achievable or we are trying something that is not in scope for the library

**Comment by steevepay** [comment]
Hi @JVaghela-Fintech,

The behavior of creating dynamic sheets is possible but it's not documented yet.
The use of variables is the only way to generate new sheets on ODS files. Before continuing, [checkout documentation about Carbone variables.](https://dev.to/steeve/carbone-tutorial-fast-and-easy-report-generator-as-fast-as-a-spaceship-54bc#variablestr-alias)
You have to define 2 variables on the template:
```
{#sheet1 = d.fruits[i].name}
{#sheet2 = d.fruits[i+1].name}
```
then insert on the sheet names navigator the variables:
```
{$sheet1} // for sheet number 1
{$sheet2}  // for sheet number 2
```
During the rendering, CarboneJS replace the variables by the repetition markers `{d.fruits[i].name}`and `{d.fruits[i+1].name}` to generate new sheets that inherit content from the first sheet. 
Following this text is an example of an ODS template, a JSON data, the javascript and a screenshot of the generated document. The goal is to generate sheets with fruit nutritional values.

**template.ods**:
<img width="777" alt="Screenshot 2019-11-25 at 11 18 05" src="https://user-images.githubusercontent.com/16964532/69532164-8aa6d100-0f75-11ea-8c68-e1c18641cbb5.png">

The JSON data to inject, **data.json**:
```JSON
{
  "fruits": [
    {
      "name": "apple",
      "nutrients": [
        {
          "type": "energy",
          "value": 52,
          "unit": "Kcal"
        },
        {
          "type": "Carbohydrates",
          "value": 13.81,
          "unit": "g"
        },
        {
          "type": "Protein",
          "value": 0.26,
          "unit": "g"
        },
        {
          "type": "Fats",
          "value": 0.17,
          "unit": "g"
        },
        {
          "type": "Cholesterol",
          "value": 0,
          "unit": "g"
        },
        {
          "type": "Dietary Fiber",
          "value": 2.4,
          "unit": "g"
        }
      ]
    },
    {
      "name": "banana",
      "nutrients": [
        {
          "type": "energy",
          "value": 89,
          "unit": "Kcal"
        },
        {
          "type": "Carbohydrates",
          "value": 22.84,
          "unit": "g"
        },
        {
          "type": "Protein",
          "value": 1.09,
          "unit": "g"
        },
        {
          "type": "Fats",
          "value": 0.33,
          "unit": "g"
        },
        {
          "type": "Cholesterol",
          "value": 0,
          "unit": "g"
        },
        {
          "type": "Dietary Fiber",
          "value": 2.6,
          "unit": "g"
        }
      ]
    },
    {
      "name": "strawberry",
      "nutrients": [
        {
          "type": "energy",
          "value": 53,
          "unit": "Kcal"
        },
        {
          "type": "Carbohydrates",
          "value": 12.75,
          "unit": "g"
        },
        {
          "type": "Protein",
          "value": 1.11,
          "unit": "g"
        },
        {
          "type": "Fats",
          "value": 0.33,
          "unit": "g"
        },
        {
          "type": "Cholesterol",
          "value": 0,
          "unit": "g"
        },
        {
          "type": "Dietary Fiber",
          "value": 3.3,
          "unit": "g"
        }
      ]
    }
  ]
}
```
index.js
```js
const fs = require("fs");
const carbone = require("carbone");

// function to generate reports
const generateFileWithCarbone = (templateFileName, buildFileName, data) => {
  carbone.render(templateFileName, data,  async (err, result) => {
    if (err) {
      return console.error(err);
    }
    await fs.writeFileSync(buildFileName, result);
  });
};

// Files
const FILE_INPUT = "./template.ods";
const FILE_OUTPUT = "./result.ods";

// Data to inject
const DATA = require("./data.json");

// Call the function
generateFileWithCarbone(FILE_INPUT, FILE_OUTPUT, DATA);

```
Finally the generated document. **result.ods**:
<img width="620" alt="Screenshot 2019-11-25 at 11 22 40" src="https://user-images.githubusercontent.com/16964532/69532359-ea9d7780-0f75-11ea-90e4-d393b896bc68.png">

Reach me if you need help.

**Comment by JVaghela-Fintech** [comment]
@steevepay Thank you very much for the explanation.
