### ISSUE TITLE
[Bug Report]: Image replacement with docx

### ISSUE THREAD

**Issue by romainstudi** [Ideolys/carbone#57]
**Environment**
Carbone.io online API

**Expected Behaviour**
Image in document should be replaced

**Actual Behaviour**
It doesn't with Microsoft Word but work with Libre Office

**Screenshots**
Doesn't work in Word
![image](https://user-images.githubusercontent.com/58422912/69953035-baffe980-14f8-11ea-8b2f-56cca42f417e.png)

Work with Libre Office
![image](https://user-images.githubusercontent.com/58422912/69953073-cb17c900-14f8-11ea-8337-0f4dd77689d2.png)

Did I miss something with Microsoft Word ?

Thank's

**Comment by dgrelaud** [comment]
Yes, we are currently working on it.

**Comment by Romain-studi** [comment]
Ok thank's

**Comment by steevepay** [comment]
Image replacement is coming with much more stability and improvements. It is coming next week (maybe earlier).

**Comment by exzizt** [comment]
> Image replacement is coming with much more stability and improvements. It is coming next week (maybe earlier).

Is it possible to insert an image into a docx yet?

**Comment by steevepay** [comment]
Yes it is, here is the documentation: https://carbone.io/documentation.html#dynamic-pictures

**Comment by exzizt** [comment]
> Yes it is, here is the documentation: https://carbone.io/documentation.html#dynamic-pictures

I see that this feature is only available for Carbone Render and Carbone Studio. Is that correct? Or is there a way my team can still use this functionality locally on our own Carbone instance?

**Comment by steevepay** [comment]
We are producing Carbone on-premise with the functionality of dynamic images and all the latest features. If you are interested, you can reach us on carbone.io or support[at]carbone.io.

**Comment by exzizt** [comment]
> We are producing Carbone on-premise with the functionality of dynamic images and all the latest features. If you are interested, you can reach us on carbone.io or support[at]carbone.io.

Ah, I see. So this functionality isn't present in the public repo?

**Comment by steevepay** [comment]
At this time, It is not going to be present in the public repo, the subject has already been discussed: https://github.com/Ideolys/carbone/issues/8

**Comment by exzizt** [comment]
> At this time, It is not going to be present in the public repo, the subject has already been discussed: #8

Has there been any talk about making image replacement available in the public repo? Our team is currently looking into a way to do this with either Carbone for free or by looking into libraries to modify the docx to insert the image before we pass it off to Carbone. Thanks!

**Comment by MutsuM** [comment]
> **Environment**
> Carbone.io online API
> 
> **Expected Behaviour**
> Image in document should be replaced
> 
> **Actual Behaviour**
> It doesn't with Microsoft Word but work with Libre Office
> 
> **Screenshots**
> Doesn't work in Word
> ![image](https://user-images.githubusercontent.com/58422912/69953035-baffe980-14f8-11ea-8b2f-56cca42f417e.png)
> 
> Work with Libre Office
> ![image](https://user-images.githubusercontent.com/58422912/69953073-cb17c900-14f8-11ea-8337-0f4dd77689d2.png)
> 
> Did I miss something with Microsoft Word ?
> 
> Thank's



The bug has been resolved by anyone?
We are trying to do the image replacement in word document, but still can't.



![image](https://user-images.githubusercontent.com/25915956/101222711-5b32a600-3658-11eb-8ab4-02089270d454.png)

**Comment by steevepay** [comment]
Hello @MutsuM, the issue is resolved.
Make sure you are using the Carbone Render API with the header: `'carbone-version' : '2'`.
If the image is still not rendering, chat with us on carbone.io (bottom right icon).
