### ISSUE TITLE
[Feature Request]: Facility to add embedded images

### ISSUE THREAD

**Issue by bradws** [Ideolys/carbone#58]
**Problem to solve**
Facility for Carbone to add embedded images in a document.

**Proposed solution**
1. User has a folder of Images (e.g. Image1.jpg, Image2.jpg, Image3.png, ... etc.)
2. The template will have an arbitrary 'dummy' embedded image already existing in the document. It exists only as a temporary placeholder for where the embedded image is to be placed. It will be named 'MyImage1'. (In order to name this dummy image in the document, right-click on the image->Properties->Options->Name). This step can be repeated many times adding any number of dummy images, as long as the naming of each the dummy images is unique.
3. API call to be something like: 
```javascript
  const fs = require('fs');
  const carbone = require('carbone');

  // Data to inject
  var data = {
    firstname : 'John',
    lastname : 'Doe',
    images: [
    { name: 'MyImage1', filename: './Images/Image1.jpg' },
    { name: 'MyImage2', filename: './Images/Image2.jpg' },
    { name: 'MyImage3', filename: './Images/Image3.png' } ]
  };

  // Generate a report using the sample template provided by carbone module
  // This LibreOffice template contains "Hello {d.firstname} {d.lastname} !"
  // Of course, you can create your own templates!
  carbone.render('./simple.odt', data, function(err, result){
    if (err) {
      return console.log(err);
    }
    // write the result
    fs.writeFileSync('result.odt', result);
  });
```

**Describe alternatives you've considered**
I would be happy to contribute and would like to implement this into Carbone. What do you think of the API call example? I'm aware this may not cater for every scenario, but it's a good start, right?

**Comment by steevepay** [comment]
Hello @bradws,

Embedded images are already working but for the Carbone Enterprise Edition, you can try this out through [Carbone Render API](https://carbone.io/api-reference.html) or [Carbone Studio](https://studio.carbone.io/). [Here is the documentation](https://carbone.io/documentation.html#dynamic-pictures-carbone-render-only-).
You may wonder why is it not included in the open-source version, [it has already been discussed](https://github.com/Ideolys/carbone/issues/8).
Thank you for your message, reach me if you need help :)

**Comment by cracautanu** [comment]
I did my own messy extension for this in 1 day. When I will have some time I will publish the solution but you should add this feature even if it's open source and unpaid...

**Comment by mazero** [comment]
@cracautanu do you have your solution to shared ?
