### ISSUE TITLE
[Bug Report]: PDF Conversion Slow

### ISSUE THREAD

**Issue by fahmisatrio** [Ideolys/carbone#61]
**Environment**
Carbone Version: 1.2.1
Node Version: 10.17.0
Browsers: chrome 79.0.xxx
Desktop OS: Centos7
libreoffice --version
LibreOffice 5.3.6.1 30(Build:1)

**Expected Behaviour**
I have invoice template (result should be not more than 2 pages) that based created on .docx format. When i call carbonejs to render the report on same format (.docx) it will only cost about  100-200ms, but when I passing options parameter to carbone and convert the report to PDF, it will cost 13-14 seconds. 

**Actual Behaviour**
PDF Conversion is slow or there is library that i need to fix?

**Comment by fahmisatrio** [comment]
`return new Promise((resolve,reject)=>{
        carbone.render(`${templFolder}/${templFile}`, data, options, function(err,result){
            if(err){
                return reject(err);
            }

            const ext = outputType;
            const filename=`${downloadFolder}/${uuid()}.${ext}`;

            if(fs.existsSync(filename)) fs.unlinkSync(filename);

            fs.writeFileSync(filename, result);
            //process.exit();
            resolve({success:true,filename});
        })
    });
`
i think it caused  by i commented this line code 
`process.exit();`

i think i need to find another approach to keep sending response but the conversion not hang up.
thanks guys

**Comment by steevepay** [comment]
Hello @fahmisatrio,

Slow PDF conversions are a known behavior because Carbone is calling the Open Office API. Only PDF rendering needs Open Office contrary to the other files format.
We have tried multiple solutions to render PDF from XML documents and OO is one of the most efficient.

If you need help, don't hesitate to reach us.
Thanks for your issue and using Carbone :)

**Comment by jawwadturabi** [comment]
Pdf conversion is very much slower, some times it takes even several minutes. Any solution for this?
