### ISSUE TITLE
[Feature Request]: Developer Environment Setup document

### ISSUE THREAD

**Issue by ajaydev12** [Ideolys/carbone#63]
Dear Carbone Contributors,

I am interested in contributing to the Carbone project. 

Do we have any instructions for setting up the development environment?

Thanks,
Ajay

**Comment by steevepay** [comment]
Hello  @ajaydev12,

First, thanks for your issue.
Carbone needs to use Node and Libre Office and you don't need anything else.
Feel free to pick any issue on the repo with the label "bug", "enhancement" or "feature" with the "[High Priority](https://github.com/Ideolys/carbone/issues?q=is%3Aopen+is%3Aissue+label%3A%22P%3A+High%22)" label. Make sure to pass all the unit tests with the command 
`npm run test` before submitting your pull request on github.

Do you have some ideas about the contribution you want to work on ?
