### ISSUE TITLE
[Feature Request]: Allow table formating such as odd rows background

### ISSUE THREAD

**Issue by ieltxualganaras** [Ideolys/carbone#67]
**Problem to solve**
Carbone ignores Auto format styles for tables such as odd/even rows styling

It would be great to have this functionality

**Comment by ieltxualganaras** [comment]
found the way to do it

**Comment by VanguardaSistemas** [comment]
Can you say how u manage to do it? I'm using CarboneJS and i didn't find a way to "zebra" my table with .odt
