### ISSUE TITLE
[Feature Request]: conditioned output as a variable not just a message(string)

### ISSUE THREAD

**Issue by seddik11** [Ideolys/carbone#70]
Hello, i want to test if a variable is null before getting one of its properties..i tried to do this {d.val:isEmpty("value is null"): d.val.id} but didn't work [Error: Formatter "d.val.id" does not exist. Do you mean "div"?] how can i manage to do this and if it is not possible we would like to see this feature in the future release..

**Comment by willemevenwel** [comment]
Did you get a response? I would also like to know this.

**Comment by steevepay** [comment]
Hello @seddik11, thank you for writing to us!
Unfortunately it is not possible to check if a variable is defined to print it. For now, you can only insert static string into arguments as explained in the [documentation](https://carbone.io/documentation.html#conditioned-output).
`{d.myvariable:ifEqual(2, “two"):print(“unknown”)}.`
This is closely related to the feature request [pass variables into formatters arguments](https://github.com/Ideolys/carbone/issues/65) and [conditional sections](https://github.com/Ideolys/carbone/issues/9).

**Comment by steevepay** [comment]
Now you can pass variables into formatters, check out the update: https://github.com/Ideolys/carbone/issues/65#issuecomment-628484730
