### ISSUE TITLE
[Bug Report]: Break line are not correctly replaced

### ISSUE THREAD

**Issue by douglascrp** [Ideolys/carbone#73]
**Environment**
Carbone Version: 1.2.1
Node Version: 10.20.0
Browsers: Any
Desktop OS: Ubuntu 18.04

**Expected Behaviour**
When using the convCRLF() function inside a template, the \n character should be replaced by the correctly line break for the template format.

**Actual Behaviour**
The function works correctly when I use a HTML form containing a textarea element, but the same does not work when I use Java to send the property with the \n character.

**Steps to reproduce**
I have a really complex Java process that I am unable to reproduce here.

**Screenshots**

![image](https://user-images.githubusercontent.com/5930258/79170464-d55ea380-7dc5-11ea-98e9-088b121e8581.png)

**Reproduction Link / Code example**
You can share your Carbone code through https://codesandbox.io/ or directly on this file.

**Other comments**

**Comment by steevepay** [comment]
Hello @douglascrp, 

First, thanks for reaching us and using Carbone!
Can you share a template example (ODT or DOCX) with the corresponding json dataset to reproduce on our side ?
How do you use Java to render the reports with Carbone?

**Comment by douglascrp** [comment]
I thank you for taking the time to analyse my use case.

Yes, sure.
For the json, this is it https://pastebin.com/PXDjz8Wg
One of the json properties I am having problem with is the decisao_comite_credito_uad
As you can see, my Java code is generating it with special characters double encoded, it seems.

For the template, you can use this https://www.dropbox.com/s/wk6ioe6bgn53e7l/template_pgc.odt?dl=0

I have a node.js application exposing the carbone API as a REST function, and my Java code is consuming it.
But I guess once I am able to identify why Java is encoding my data like that, maybe my commit is not needed.

Feel free to ask more questions.

**Comment by steevepay** [comment]
The data "decisao_comite_credito_pa" should be simplified by:
`admin(Test Administrator) está EM ACORDO;\n\nParecer:\n\nAprovado\n\n__________________\n\n`
Then in your template, add double quotes around the marker:
`"{d.decisao_comite_credito_pa:convCRLF()}"`

**Comment by douglascrp** [comment]
> Maybe you can disable the JAVA encoding, let me know if it is working.

Yes, I tried that, in several ways, and I could not make it work. I have no idea why it is sending the data like that, because when I debug my Java code, the value is right... the problem happens when the Spring framework creates the request, and that is the when I could not understand.
I know the "fix" I am proposing would not be required at all if the text were right.
I will keep trying, and I will let you know it I am able to change that behaviour.

**Comment by douglascrp** [comment]
Ok, I have found the what was causing the problem, and for sure, it was on my side, so, not carbone related.
I am closing this now... thank you for your attention and for this awesome project.
