### ISSUE TITLE
Conditional Rendering in Array

### ISSUE THREAD

**Issue by rufus01** [Ideolys/carbone#76]
Hi there,

is there a way to conditional render column B depending on value in Column A in an simple array ?
The use case is: I only want to show the name for a specific type.
I have tried:
{d.line[i].type:ifEqual(product ,{d.line[i].name})}
{d.line[i+1].type:ifEqual( product,{d.line[i+1].name})}

But only the second part, d.line.name, gets rendered.

Help or suggestions, would be appreciated!

Thanks
Rufus

**Comment by steevepay** [comment]
Hi @rufus01, thank you for reaching us!
We have deployed a new version which makes your use case working. It is available on the [v2 branch](https://github.com/Ideolys/carbone/tree/v2.0) on Github or npm: `npm install carbone@2.0.0-beta.0`.
And also you have to change your template to:
```
{d.line[i].type:ifEqual(product, .name)}
{d.line[i+1].type)}
```
More examples are available on the [changelog](https://github.com/Ideolys/carbone/blob/v2.0/CHANGELOG.md#v20x).
Reach me if you need help.

**Comment by steevepay** [comment]
The fix has been pushed on master.
