### ISSUE TITLE
[Feature Request]: Electron compatibility

### ISSUE THREAD

**Issue by Rick9595** [Ideolys/carbone#77]
I'm using Carbone with Electron, if I run the app from command line everything go well, if i wrap the app with electron packager to get an .exe, Carbone don't work anymore. There's something I can do? thank you

**Comment by steevepay** [comment]
Hi @Rick9595, thank you for using Carbone!
I have never tried an Electron app with Carbone, do you have any logs?
Are you using Carbone on the server side?
If you are exporting PDF, did you install Python and OpenOffice?

**Comment by Rick9595** [comment]
Hi, thank you for reply, I don't get any error or callback from "carbone.render", i'm using openoffice for the conversion, it not work only if I wrap the app with electron packager, otherwise everything go well

thank you

**Comment by steevepay** [comment]
Can you share with me a sample project reproducing the issue?
My email is available on my Github profile.

**Comment by steevepay** [comment]
The problem was probably coming from the "asar" option which creates an archive of the source code.
By disabling it, Carbone is working well.
