### ISSUE TITLE
[Feature Rest]: Support for dynamic images

### ISSUE THREAD

**Issue by pauloruben** [Ideolys/carbone#78]
Are there any plans to support dynamic images in the open source - Carbone JS?
I noticed there is a beta available only on SaaS version - renderer and it isn't clear if the open source will support it in the future.

Thanks.

**Comment by steevepay** [comment]
Hi @pauloruben,
For now, we don't plan to share the support of dynamic images in the open source version.
We already discused about it https://github.com/Ideolys/carbone/issues/8
Thank you for reaching us!
