### ISSUE TITLE
[Bug Report]: Error when printing report with arrays in data

### ISSUE THREAD

**Issue by LoreScianatico** [Ideolys/carbone#79]
**Environment**
Carbone Version: 2.0.0-beta.5
Node Version: 10.15.1
Browsers: not relevant
Desktop OS: Windows 10

**Expected Behaviour**
Report is printed and file can be opened

**Actual Behaviour**
The file cannot be opened and an error is printed by Microsoft Word

**Steps to reproduce**
Steps to reproduce the bug:
1. Create a report with a bullet list
2. Create a json data for this report, with an array field
3. Print data from array using the usual syntax [i] and [i+1]
4. Print it using a Carbone.io server with Node.js

Screenshot of the error:

![image](https://user-images.githubusercontent.com/10486743/84148715-a9773b80-aa5f-11ea-90ae-918a1720cf2e.png)

**Other comments**
Sorry for the error in Italian. Essentially it says that it is not possible to open the file and it suggests to verify authorizations on file, check memory and so on. Same template with version 1.2.1 works. We are trying to develop a server application using 2.0.0-beta.5 because we need some features from the newest version.

**Comment by dgrelaud** [comment]
We are going to publish the beta.6 tonight with other bug-fixes.

I will test your case before publishing.

**Comment by dgrelaud** [comment]
I didn't have the time to test on Windows yet but the carbone@2.0.0-beta.6 is published with a patch about LibreOffice detection on Windows and some other bugs.

Can you retry please?

**Comment by LoreScianatico** [comment]
Yes, I'll try it again. I'll let you know, thank you!

**Comment by LoreScianatico** [comment]
Sorry, still broken... is there something you need from me to check this issue?

**Comment by dgrelaud** [comment]
Yes, can you share a sample of your template and data please?

**Comment by LoreScianatico** [comment]
Is there a way for sharing privately with you template and data?

**Comment by dgrelaud** [comment]
Yes, you can send me an email at support@carbone.io
We could sign a NDA if you prefer. And to improve even more the security, try to remove every sensible data, part of the document, ...

**Comment by dgrelaud** [comment]
Hello, can you try the new beta.7 please? 
It should be better. It contains a bugfix related to your template (if-block nearby loop section).

Be careful , we've changed a little bit the behaviour of formatters ifGT, ifGTE, ifLT, ifLTE. They cannot be used directly to test the length of an array. You should use ifEM (ifEmpty) instead.

**Comment by LoreScianatico** [comment]
Hello, we have tested it right now. It works.

Thank you for your support!
