### ISSUE TITLE
It doesn't work without internet connection

### ISSUE THREAD

**Issue by Daniil-Sokolov** [Ideolys/carbone#80]
I use this module in Windows XP
And this module doesn't work when I have no internet connection

I think what the reason of this error is in "integrity" parameter in package.json

**Comment by steevepay** [comment]
Hi @Daniil-Sokolov, thank you for reaching us. Before continuing, I need details:
- Which version of Carbone are you using?
- Have you tried on a different system?
- Do you have logs or errors? 
- Node version?
