### ISSUE TITLE
Cannot replicate Tutorial Bi-directionnal loop

### ISSUE THREAD

**Issue by tomspeed22** [Ideolys/carbone#81]
Hello, 
I do not understand why the Bi-Directional Does not work in Carbon Studio. 
Below the Json and the code pasted in Excel and Docx File. 
Thanks for your help if I am making a mistake or there is a bug.

-----------------

{ d.cars[i].models[i].brand } | { d.cars[i+1].models[i].brand}
{ d.cars[i].models[i].name} | { d.cars[i+1].models[i].name}
{ d.cars[i].models[i+1].name} | { d.cars[i+1].models[i+1].name}

--------------------------------

{
  "cars": [
    {
      "brand": "Toyota",
      "models": [
        {
          "name": "Prius 2"
        },
        {
          "name": "Prius 3"
        }
      ]
    },
    {
      "brand": "Tesla",
      "models": [
        {
          "name": "S"
        },
        {
          "name": "X"
        }
      ]
    },
    {
      "brand": "Lumeneo",
      "models": [
        {
          "name": "Smera"
        },
        {
          "name": "Néoma"
        }
      ]
    }
  ]
}

**Comment by steevepay** [comment]
Hi @tomspeed22, thank you for reaching us!
This is a known issue #45, here is a temporary solution until we fix it: https://github.com/Ideolys/carbone/issues/45#issuecomment-550362054
