### ISSUE TITLE
[Feature Request]: Table of contents

### ISSUE THREAD

**Issue by LoreScianatico** [Ideolys/carbone#82]
**Problem to solve**
Add the possibility of automatically create a summary/table of contents for a docx template. Items in the summary/table of contents should be omitted in case of conditional printing.

**Proposed solution**
Maybe it should be considered the idea of introducing special syntax for marking items for a table of contents.

**Describe alternatives you've considered**
We have tried creating a table of contents with Microsoft Word functionalities but if sections are conditional ones the report gives an error when opened after printing.

**Additional context**
We are printing a long report made up with various sections. Some sections can be omitted if there is no significant data to be printed. Hence, we are trying to define a summery/table of contents in the first document pages but if we try to print the summary probably it is not updated considering those conditional sections and then an error is thrown, the usual one that says that file is corrupted and can't be opened.

**Comment by steevepay** [comment]
Hi @LoreScianatico, 
It is possible to create a table of content dynamically only for PDF export. On rendering, Libre Office refreshes the table of content based on the new content. It does not work with other export formats. We are going to investigate your request and come back to you :) 
You can share with us your template to fix the issue (reach me by mail on my GitHub profile).

**Comment by LoreScianatico** [comment]
Hi @steevepay, 
thank you for your answer. I am going to send you a sample template and data to show you my needs.

**Comment by steevepay** [comment]
To share a temporary solution, it is possible to force the refresh of the table of content if you are exporting:
- from DOCX/ODT to PDF
- from DOCX to ODT or from ODT to DOCX
We are investigating to create a rendering option to force the refresh for the same file type, for example, export from ODT to ODT.

**Comment by steevepay** [comment]
A new rendering option is available: `hardRefresh` on the latest version v2.1.0! You can use this option to force the refresh of the table of content from a DOCX template to a DOCX report ;)

**Comment by LoreScianatico** [comment]
This is amazing! Thank you!
