### ISSUE TITLE
[Bug Report]: Math formatter

### ISSUE THREAD

**Issue by met-pub** [Ideolys/carbone#83]
**Environment**
Carbone Version: [2.0.0]
Node Version: [Node 10.19.0]
Desktop OS: [Ubuntu 18]

**Expected Behaviour**
d: { "data":  { "a": 1, "b": 2 } }

{#da = d.data}

{$da.a:add({$da.b})}
=> Expected: 3

**Actual Behaviour**
{$da.a:add({$da.b})}
=> {$da.a:add(2)}

**Comment by steevepay** [comment]
Hi @met-pub, thank you for reaching us!
Carbone passes data to formatters if parameters start with a dot . and is not surrounded by quotes.
To make your example work, you have to change to:
`{#da = d.data} {$da.a:add(.b)}`
If you need to access to parent properties, use 2 dots.
Here is an example to read parent objects and their children attributes (no limit in depth):
`{d.subArray[i].qtyE:add(..subObject.qtyC)}`

**Comment by met-pub** [comment]
Thank you for quick reply. Let's say:
`d: [ { "a": 1, "b": 2 }, {"c": 3, "d": 4} ]`
`{#d0 = d[i=0]}  {#d1 = d[i=1]}`
I'd like to know how to get d.a + d.c, i.e.,  
`{$d0.a:add(${d1.c})}`
Thanks again.

**Comment by steevepay** [comment]
Unfortunately, it is not possible to pass a property coming from an array as a parameter, only properties from objects.
