### ISSUE TITLE
[Bug Report]: Currency format for pt-br is wrong

### ISSUE THREAD

**Issue by douglascrp** [Ideolys/carbone#87]
**Environment**
Carbone Version: 2.0.0
Node Version: v13.12.0

**Expected Behaviour**
When using the formatC function with Brazilian Portuguese (pt-br), the right format for the value is R$ 1 000,00

**Actual Behaviour**
The value is formated as 1 000,00 R$.

**Comment by steevepay** [comment]
Hi @douglascrp, thank you for your report, we are going to merge your fix :)
