### ISSUE TITLE
[Feature Request]: Allow calculating and then formatting values

### ISSUE THREAD

**Issue by douglascrp** [Ideolys/carbone#89]
**Problem to solve**
We have a case with two float properties, like price and taxes, and then we would like to sum the values, using the add function, and after that, format the result as currency.

**Proposed solution**
We tried to achieve that by using something like
{d.price:add(d.taxes):formatC()}

But the result is a NaN value.

**Describe alternatives you've considered**
We also tried the following
{(d.price:add(d.taxes)):formatC()}

hopping it would use the sentence between () before performing the formatting, but that seems to be invalid.

**Comment by douglascrp** [comment]
Thank you for taking the time to answer.

Yes, that's it... it worked like a charm.

About the documentation, yes, I think it could be improved in some way.
In this case, as I was looking at the formats section, I would never think about reading the dynamic section.
Maybe a simple mention with something like "for chaining formatters, check the dynamic-parameters docs"

I am going to close the issue, as you answer solved it.

Thank you so much again.

**Comment by fiuzatayna** [comment]
> Hello,
> 
> Try with `{d.price:add(.taxes):formatC()}`
> 
> You must not repeat `d.` when injecting variable in formatters. Use only relative path to the current object with one ore multiple dots. Some examples here : https://carbone.io/documentation.html#dynamic-parameters
> 
> Do you think we should improve the documentation about that?
> 
> At least, I've created an issue to return a "crystal-clear human error" when people try to inject variable with absolute path from `d.` 😉

This should definitely be reinforced in the [simple mathematics page](https://carbone.io/documentation/design/computation/simple-mathematics.html) with examples.

This solved my issue 👍 

Thanks for all the work.
