### ISSUE TITLE
[EMERGENCY]: Website down

### ISSUE THREAD

**Issue by Aarbel** [Ideolys/carbone#92]
@dgrelaud @steevepay 

carbone.io is down.

Is your service reliable ?

**Comment by dgrelaud** [comment]
It is ok for us (no alerts).
The website is inaccessible for you? 

The service Carbone Render is spread across multiple servers (no SPF).

The website carbone.io is a static website but the availability could be improved with a worldwide CDN. 
We are working on it.

**Comment by Aarbel** [comment]
Looks like a network problem on my side, sorry for the alert.
