### ISSUE TITLE
[Bug Report]: how to deal with numerics in office documents

### ISSUE THREAD

**Issue by Toub** [Ideolys/carbone#93]
**Environment**
Carbone Version: 2.1.0
Node Version: 10.20.1
Desktop OS: Debian Stretch in docker (host env: linux)
LibreOffice: 6.1.5.2 (Debian) in __french__

**Expected Behaviour**
When using the following data model:

```js
const model = {
    some_number: 5.5,
}
```

And the following template:

```js
{d.some_number}
```

When opening the generated spreadsheet, I would expect the cell value to be a number (e.g. to be able to format it as %).

**Actual Behaviour**

When opening the document, the number value is taken as a string, as the comma delimiter is "." instead of "," (french version of LibreOffice).

The generated content.xml contains:

```xml
<table:table-cell table:style-name="ce45" office:value-type="string" calcext:value-type="string"><text:p>5.5</text:p></table:table-cell>
```

while a manually entered number in LibreOffice FR is:

```xml
<table:table-cell office:value-type="float" office:value="6.6" calcext:value-type="float"><text:p>6,6</text:p></table:table-cell>
```

You can see that `office:value` does not use the same delimiter as `<text:p>` content.

**Steps to reproduce**

See `Expected Behaviour`

**Screenshots**

**Other comments**

I am new with open-document format, and I am new with carbone.

I understand that carbone does not care about a specific format, and simply try to replace the template string in the xml document.

In my original template, I have:

```xml
<table:table-cell table:style-name="ce45" office:value-type="string" calcext:value-type="string"><text:p>{d.some_number}</text:p></table:table-cell>
```

However, this is a simple use case, so I am surprised not to find a simple workaround for this.

Do I have to manually update it to:

```xml
<table:table-cell table:style-name="ce45" office:value-type="float" office:value="{d.some_number}" calcext:value-type="float"><text:p>{d.some_number}</text:p></table:table-cell>
```
?

Anything I missed?

**Comment by steevepay** [comment]
Hello, 
The subject has already been discussed on Github: https://github.com/Ideolys/carbone/issues/13
You can use the formatter `:formatN()` to keep the number as a number type, such as: `{d.some_number:formatN()}`. Then you can apply any number format from your text editor. I advise you to read the documentation about `formatN`: https://carbone.io/documentation.html#formatn-precision-

**Comment by Toub** [comment]
Thanks for your fast answer, you saved my day!

May I suggest to add a warning to the documentation with an explicit message about numbers with spreadsheet?

In top of `Number manipulation` section?

I am closing the issue.

ps: by the way, great library, I love the approach!

**Comment by Toub** [comment]
The only issue I see with `:formatN()` is that "0" value is printed if model value is "null" or "undefined", while I would expect to have an empty cell.

Do you want me to fill a specific issue about it?
 
Is there a workaround? I am playing with `Conditioned output` but I can't make it work.

```js
{$my_number:ifEmpty()} // OK: value is not printed if null 
{$my_number:ifEmpty():formatN()} // KO: '0' is printed if null
```

**Comment by Toub** [comment]
According to https://github.com/Ideolys/carbone/issues/13#issuecomment-584256385, date also have a special type in open document format.

Do we have a similar solution to have true dates supported in spreadsheets? (I can also open a separate issue for this one)
