### ISSUE TITLE
Question about table: multiple rows in one cell

### ISSUE THREAD

**Issue by Baddhizm** [Ideolys/carbone#98]
```javascript
var data = [
    {
        name: 'First',
        values: [{
            a: '30',
            b: '50'
        }, {
            a: '32',
            b: '42'
        }, {
            a: '44',
            b: '12'
        }]
    },
    {
        name: 'Second',
        values: [{
            a: '23',
            b: '54'
        }, {
            a: '12',
            b: '32'
        }]
    }
];
```
Expected result:
![image](https://user-images.githubusercontent.com/34471467/94026027-d6a6ea00-fdc1-11ea-93b7-81cd979ddc97.png)

How can i do this with `*.odt` format?

**Comment by Baddhizm** [comment]
I'm trying this:
![image](https://user-images.githubusercontent.com/34471467/94029909-ed4f4000-fdc5-11ea-8b66-c1789c8791d3.png)

But result is:
![image](https://user-images.githubusercontent.com/34471467/94029934-f213f400-fdc5-11ea-920d-0fd45d6c36a0.png)

**Comment by dgrelaud** [comment]
Thank you for using Carbone.

Yes, the generic algorithm of Carbone does not manage very well this case (row span).
It could be improved one day but it need special code to manage specification of each template format (xlsx, ods, ...)

A workaround is to nest arrays like this in Word or LibreOffice:

![image](https://user-images.githubusercontent.com/1288509/95311038-656d3980-088d-11eb-8cc7-1bbecd9ccca5.png)

Then, if you carefully manages margins and  borders of cells, it can be invisible in the final result.
